repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
helmDefaults:
  wait: true
  waitForJobs: true
releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.16.1
    values:
      - crds:
          enabled: true
  - name: jaeger
    namespace: jaeger
    chart: jaegertracing/jaeger-operator
    version: 2.57.0
    values:
      - rbac:
          clusterRole: true
    disableValidationOnInstall: true
    needs:
      - cert-manager/cert-manager
  - name: prometheus
    namespace: prometheus
    chart: prometheus-community/prometheus
    version: 26.0.0
    values:
      - alertmanager:
          enabled: false
        kube-state-metrics:
          enabled: false
        prometheus-node-exporter:
          enabled: false
  - name: grafana-operator
    namespace: grafana-operator
    chart: oci://ghcr.io/grafana/helm-charts/grafana-operator
    version: v5.15.1
  - name: csi-interposer
    namespace: csi-interposer
    chart: ./helm
    values:
      - image:
          repository: docker.io/library/csi-node
          tag: latest
    disableValidationOnInstall: true
    needs:
      - jaeger/jaeger
      - grafana-operator/grafana-operator
      - prometheus/prometheus
