kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-driver-interposer-cluster-role-binding
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-interposer-role
subjects:
- kind: ServiceAccount
  name: csi-interposer-sa
  namespace: {{ .Release.Namespace }}
