kind: GrafanaDatasource
apiVersion: grafana.integreatly.org/v1beta1
metadata:
  name: jaeger
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  datasource:
    access: proxy
    name: Jaeger
    type: jaeger
    url: http://jaeger-default-collector-headless:16686
