kind: ServiceAccount
apiVersion: v1
metadata:
  name: csi-interposer-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
