# Reference: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/csi-driver-v1/
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: interposer.csi.example.com
spec:
  attachRequired: false
  fsGroupPolicy: None
  podInfoOnMount: true
  requiresRepublish: false
  seLinuxMount: false
  storageCapacity: false
  volumeLifecycleModes:
    - Ephemeral
