kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Job
apiVersion: batch/v1
metadata:
  name: minio
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: minio
          image: quay.io/minio/minio:latest
          args: [ "server", "/data" ]
          restartPolicy: Always
          startupProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: "/data"
              name: data
      containers:
        - name: warp
          image: quay.io/minio/warp:latest
          args:
            - mixed
            - --access-key=minioadmin
            - --secret-key=minioadmin
            - --autoterm
            - --objects=10
            - --concurrent=5
            - --obj.size=1k
      volumes:
        - name: data
          csi:
            driver: interposer.csi.example.com
            volumeAttributes:
              persistentVolumeClaimName: minio-pvc
              command: interposer --foreground $(SOURCE_PATH) $(TARGET_PATH)
              otlpEndpoint: jaeger-default-collector-headless:4317
