name: E2E test

on:
  push:

jobs:
  basic-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: helm/kind-action@v1
        with:
          cluster_name: kind
      - name: Build CSI plugin image
        run: |
          nix build .#csi-node -vL
      - name: Load CSI plugin image into kind
        run: |
          kind load image-archive <(./result)
      - name: Install jaeger operator
        run: |
          helm repo add jetstack https://charts.jetstack.io --force-update
          helm install \
            cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --atomic \
            --version v1.16.1 \
            --set crds.enabled=true

          helm repo add jaegertracing https://jaegertracing.github.io/helm-charts --force-update
          helm install \
            jaeger jaegertracing/jaeger-operator \
            --namespace jaeger \
            --create-namespace \
            --atomic \
            --version v2.57.0 \
            --set rbac.clusterRole=true

          helm install \
            grafana-operator oci://ghcr.io/grafana/helm-charts/grafana-operator \
            --namespace grafana-operator \
            --create-namespace \
            --atomic \
            --version v5.15.1
      - name: Apply CSI plugin manifests
        run: |
          helm install \
            csi-interposer ./helm \
            --namespace csi-interposer \
            --create-namespace \
            --atomic

          kubectl -n csi-interposer wait jaegers.jaegertracing.io jaeger-default --for=jsonpath='{.status.phase}'=Running
      - name: Apply CSI example manifests
        run: |
          kubectl apply -k examples
      - name: Wait for test job to complete
        run: |
          kubectl wait jobs/minio --for=condition=complete --timeout=600s
          kubectl logs jobs/minio
      - name: Cleanup CSI example manifests
        run: |
          kubectl delete -k examples
