name: E2E test

on:
  push:

jobs:
  basic-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: helm/kind-action@v1
        with:
          cluster_name: kind
      - name: Build CSI plugin image
        run: |
          nix build .#csi-node -vL
      - name: Load CSI plugin image into kind
        run: |
          kind load image-archive <(./result)
      - uses: helmfile/helmfile-action@main
        with:
          helmfile-args: apply --skip-diff-on-install
      - name: Apply CSI example manifests
        run: |
          kubectl -n csi-interposer rollout status daemonset csi-interposer
          kubectl -n csi-interposer wait jaegers.jaegertracing.io jaeger-default \
            --for=jsonpath='{.status.phase}'=Running
          kubectl apply -k examples
      - name: Wait for test job to complete
        run: |
          kubectl wait jobs/minio --for=condition=complete --timeout=600s
          kubectl logs jobs/minio
      - name: Cleanup CSI example manifests
        run: |
          kubectl delete -k examples
