name: E2E test

on:
  push:

jobs:
  basic-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: helm/kind-action@v1
        with:
          cluster_name: kind
      - name: Build CSI plugin image
        run: |
          nix build .#csi-node -vL
      - name: Load CSI plugin image into kind
        run: |
          kind load image-archive <(./result)
      - name: Install jaeger operator
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.16.1/cert-manager.yaml
          kubectl wait customresourcedefinitions.apiextensions.k8s.io \
            certificates.cert-manager.io --for=condition=established
          kubectl wait customresourcedefinitions.apiextensions.k8s.io \
            issuers.cert-manager.io --for=condition=established
          kubectl -n cert-manager wait deployments.apps/cert-manager-webhook --for=condition=available

          kubectl create namespace observability
          kubectl apply -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.62.0/jaeger-operator.yaml
          kubectl -n observability wait deployments.apps/jaeger-operator --for=condition=available
      - name: Apply CSI plugin manifests
        run: |
          kubectl apply -k deploy
          kubectl -n csi-interposer rollout status daemonset csi-interposer
          kubectl wait jaegers.jaegertracing.io jaeger-default --for=jsonpath='{.status.phase}'=Running
      - name: Apply CSI example manifests
        run: |
          kubectl apply -k examples
      - name: Wait for test job to complete
        run: |
          kubectl wait jobs/minio --for=condition=complete --timeout=600s
          kubectl logs jobs/minio
      - name: Cleanup CSI example manifests
        run: |
          kubectl delete -k examples
